# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 170ba4b71792d7c5f411ce71765c0a49b4c57f6278e2343a817f1f300cf75a915f4b3d5c87ec6a5868935d74d614e6f7aabedc0a5f19c7fc2f411b640c3ba914
  recaptcha_key: 6Le8SwgUAAAAALXwUmXrYtCOx7XB07tp7PmqlLTL
  recaptcha_secret: 6Le8SwgUAAAAAJMXWxo8ikorxH-FJBUQWF8Kza94

test:
  secret_key_base: 70f5008dd277cb488bfa0c979a4b42f633324fe7f551c65937022767888c6dd4df923c2a0f47cb81f93b3caf0910166feb1986c6ed9c2e975c1bd5163eec5edf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  recaptcha_key: <%= ENV["RECAPTCHA_KEY"] %>
  recaptcha_secret: <%= ENV["RECAPTCHA_SECRET"] %>
